### ISSUE TITLE
Cookie not persisting on localhost

### ISSUE THREAD

**Issue by leekelleher** [pegasus-web/age-gate#20]
When testing on localhost, the `pwag` cookie isn't being set. This may be related to the new subdomain feature.

> **To be investigated further.**

**Comment by danbramall** [comment]
It is indeed (see https://stackoverflow.com/questions/1134290/cookies-on-localhost-with-explicit-domain). I didn't come across a neat way to get the cookie to persist on localhost, although I didn't spend long investigating tbh :)  I just set up full IIS to test locally with a 'proper' domain.

**Comment by leekelleher** [comment]
Closing this, we can discuss on PR #21.
